name: Download Solution from Source

on:
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  download-solution:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Install Power Platform CLI from NuGet
        run: |
          nuget install Microsoft.PowerApps.CLI -OutputDirectory tools
          # Set the pac CLI path correctly for Windows
          $pacPath = "$($pwd.Path)\tools\Microsoft.PowerApps.CLI\tools"
          Write-Host "Adding pac CLI to PATH: $pacPath"
          [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';' + $pacPath, [System.EnvironmentVariableTarget]::Process)
        shell: pwsh

      # Run pac CLI directly from full path
      - name: Run PAC CLI with Full Path
        run: |
          .\tools\Microsoft.PowerApps.CLI\tools\pac.exe --version
        shell: pwsh

      # Optional: Debug to check if pac.exe is in PATH and check the PATH variable
      - name: Debug PATH and PAC
        run: |
          echo $env:PATH
          Get-ChildItem "$($pwd.Path)\tools\Microsoft.PowerApps.CLI\tools" | Where-Object { $_.Name -eq "pac.exe" }
        shell: pwsh

      - name: Verify pac installation
        run: |
          pac --version
        shell: pwsh

      - name: Verify PAC CLI Installation with Full Path
        run: |
          $(pwd)\tools\Microsoft.PowerApps.CLI\tools\pac.exe --version
        shell: pwsh
      
      - name: Run downloadFromSource.ps1
        shell: pwsh
        run: |
          .\pipelineScripts\downloadFromSource.ps1 -solutionName "Dataverse4TeamsDemo" -exportDirectory ".\demo\dataverse4TeamsDemo" -sourceEnv "1838fca4-6258-e6b8-a710-60838df81aa3" -unpackDirectory ".\demo\dataverse4TeamsDemo\unpacked"
     
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Downloaded and unpacked solution changes"
        
