name: Download Solution from Source

on:
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  download-solution:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Install Power Platform CLI
        run: |
          npm install -g pac-cli
          
      - name: Run downloadFromSource.ps1
        shell: pwsh
        run: |
          .\pipelineScripts\downloadFromSource.ps1 -solutionName "Dataverse4TeamsDemo" -exportDirectory ".\demo\dataverse4TeamsDemo" -sourceEnv "1838fca4-6258-e6b8-a710-60838df81aa3" -unpackDirectory ".\demo\dataverse4TeamsDemo\unpacked"
