name: Upload Solution to Target

on:
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  upload-solution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Install Power Platform CLI
        run: |
          npm install -g pac-cli

      - name: Run releaseToTarget.ps1
        shell: pwsh
        run: |
          .\pipelineScripts\releaseToTarget.ps1 -solutionName "Dataverse4TeamsDemo" -unpackDirectory ".\demo\dataverse4TeamsDemo\unpacked" -exportDirectory ".\demo\dataverse4TeamsDemo" -targetEnvironment 5fc7b0a0-dc6e-e682-8886-bad6dac246a7 -managed
